### ISSUE TITLE
½ Free Periods are colorized as having a class that period

### ISSUE THREAD

**Issue by jbis9051** [JRProgramming/Blind-Brook-Block-Schedule-Generator#6]
If a user submit a schedule contains a ½ free period (comes out to 3/8 days having a free) the free is marked as the same color as the class that exists on the other days. 

<img width="1013" alt="Screen Shot 2019-09-13 at 10 10 55 PM" src="https://user-images.githubusercontent.com/32957090/64902329-62484f80-d673-11e9-8733-ca65e0e00fd1.png">

**Comment by JRProgramming** [comment]
Now associates a color with a class. Issue is fixed

**Comment by jbis9051** [comment]
Your mixing up CSS and the DOM API. 

> `document.getElementsByTagName("TD")[i].setAttribute("style","backgroundColor: white;")`

Firstly, `backgroundColor` isn't a valid CSS property. The correct property is [`background-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color). Currently, the css style is invalid and therefore ignored by the browser. The browser falls back to its default settings which is `transparent`. Since the `body`'s background color is white, the box appears white however it is not truly white, it is transparent. Additionally, manually changing the `style` attribute is not the best way to modify styles of an element. Instead, use the DOM API's [`style` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style):

> document.getElementsByTagName("TD")[I].style.backgroundColor = "white";

However, using inline styles are not great practice because they are difficult the manage and scale and the browser can't cache them. Instead use an external CSS stylesheet with a class selector:

```
/* stylesheet.css */
.class-name {
     background-color: white;
     /* or */
     background-color: white;
}

/* index.html */
<head>
     [...]
     <link rel="stylesheet" href="stylesheet.css">
     [...]
</head>
```

**Comment by JRProgramming** [comment]
I fixed the first part, not sure what you mean by 
> However, using inline styles are not great practice because they are difficult the manage and scale and the browser can't cache them. Instead use an external CSS stylesheet with a class selector:
> 
> /* stylesheet.css */
> .class-name {
>      background-color: white;
>      /* or */
>      background-color: white;
> }
> 
> /* index.html */
> <head>
>      [...]
>      <link rel="stylesheet" href="stylesheet.css">
>      [...]
> </head>

**Comment by jbis9051** [comment]
There are three ways to apply styles to an HTML element.

1. **Inline Styles**

You can write CSS inside the `style` attribute. These are called [inline styles](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style).

However note what it says on MDN:

> Note that it is recommended for styles to be defined in a separate file or files.

There are two main issues with this. Firstly, it is difficult to manage. On large sites with extensive CSS having to change the inline styles for 50 elements is much more difficult than changing it once in a style sheet. Additionally, writing inline styles is a WET practice. You should try to write [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) code. Your page will also be larger and take longer load time. Secondly, the browser can't cache inline styles. Every single time you page loads the browser has to read the styles for your page instead of being able to cache them on disk. This goes towards the larger page issue also.

2. **`<style>` element**

The [`style`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style) element can go in the body or head but it suggested that it goes in the head.
```
<head>
<style>
     .class {
          color: blue;
      }
</style>
</head>
<body>
      <h1 class="class">A Title</h1>
</body>
```

However note what it says:

> Even better, put your styles in external stylesheets and apply them using <link> elements.

This makes manning a single page MUCH easier and can reduce the size of the page. Additionally you will be writing less WET code. However this still doesn't fix two issues. Firstly, most times multiple pages on a site will requires same styles for same classes. Copy and paste the `<style>` element is more WET code. Additionally, the page can still get very large when you have more CSS. If you website takes too long to load, users will click of it. 


3. **External Stylesheet**

The best method and suggested method is creating an external stylesheet as suggested in both MDN articles. Using the [`<link>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) element in the `<head>`, you can include an external style sheet.

Create the file `style.css` and put the following it it:

```
 .class {
          color: blue;
  }
```

Then in `index.html`:

```
<head>
<link rel="stylesheet" href="style.css">
</head>
<body>
<h1 class="class">A Tile</h1>
</body>
```

This fixed a couple different issues. It separates your content from your presentation, allows the browser to cache the style sheet (so even if its used on multiple pages, only one request is made to the server and the browser can load the page much faster), it can be included on multiple pages (DRY code).

The only issue with this method in the inherit issue with caching: If you update the stylesheet the browser won't know to re-request it and will not have the updated stylesheet. There are a couple ways to solve that:

1. Use headers. I am not gonna get into this because you don't have your own server and you can't control GitHub's HTTP headers.

2. Appending `?v=[VERSION]` to your `link` element. For example go from:


```
<link rel="stylesheet" href="style.css?v=1.0">
```
to
```
<link rel="stylesheet" href="style.css?v=2.0">
```

The reason this works is for the two following reasons:

1. The `?` character in a URL starts the [`query string`](https://en.wikipedia.org/wiki/Query_string). It should not change the destination page (unless you have a special config which you can't because you don't have your own server). The `v=[VERSION]` is simply passing a variable `v` with the version. This part doesn't really matter as long as it changes every time you update your style sheet. 

2. If the browser sees a different URL (the query string is included in a URL) than it will send another request to the server. Since `style.css?v=1.0` is different form `style.css?v=2.0` than it will force another request and cache the new version.

**I suggest reading all the articles linked in the post and reading up on basic HTML,CSS, JS. If you have been using w3schools to learn these things, don't. It is an awful resource that doesn't teach good practice. Instead using MDN and StackOverflow. Start [here](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web).**

**Comment by jbis9051** [comment]
Also, what issue did you see with portrait printing?

**Comment by JRProgramming** [comment]
Hey,

I see that in your website, you added the middle school feature and the teachers feature. I know that I don’t have any license or any legal stuff to protect this, so technically you can do this. However, it would be nice to ask me before using it or at least acknowledge that this idea came from me.

I was leaning towards the idea of combining, but now that you just took some my ideas, I don’t see any point if you’re going to grab every feature that I use.

Not mad, but I would like to get at least something

**Comment by jbis9051** [comment]
I didn't steal your code and I didn't *steal* your idea. The scheduler is supposed to work with middle and high school. I didn't realize middle school was on different schedule. Once I did I implemented it. The teachers thing I just added because people can forget teachers names. I didn't mean to take it from you. And by putting your code on GitHub without a license or anything you are implicitly giving people permission to use your code and ideas.

Again, I didn't try to grab any features. I am not trying to work against you.

If you are expecting money, sorry not happening. If you want credit, I'm not sure for what. Again, I didn't use your code. I can't even use your code. It's not compatible. My HTML is generated server side, yours client side. You interact with the DOM, I don't because I can't because it's done server side.

**Comment by JRProgramming** [comment]
I never mentioned stealing my code. Of course it’s impossible to drop my code into your program.

Sorry I took it the wrong way. I’m going to stop working on the site this week to do some other things, but I like the idea of combining. Let’s talk about that next week

Sorry I phrased my last email poorly
